#!/usr/bin/env python

'Convert .optgeom files to xyz or gjf files for visualization.'

import os
import sys

#unbuffered standard out
os.environ["PYTHONUNBUFFERED"]="1"

argc = len(sys.argv)
if argc == 1 or (argc == 2 and sys.argv[1][0] == '-'):
    print('Usage: optgeom2xyz [-option] filename')
    print('')
    print('Valid options:')
    print(' -xyz Convert to xyz format (default).')
    print(' -gjf Convert to gjf format.')
    print('')
    print('If filename ends with .optgeom, the ".optgeom" can be omitted.')
    print('')
    exit(1)

do_gjf = False
if sys.argv[1][0] == '-':
    if sys.argv[1][1:].lower() == 'gjf':
        do_gjf = True
    sys.argv[1:] = sys.argv[2:]

for i in range(1,len(sys.argv)):
    # Open input file
    filename = sys.argv[1]
    try:
        fn = open(filename,'r')
    except IOError:
        filename = filename + '.optgeom'
        try:
            fn = open(filename,'r')
        except IOError:
            print('Fatal error: cannot open input file ' + filename + ' !')
            exit(2)

    # Open output file
    if do_gjf:
        suffix = '.gjf'
    else:
        suffix = '.xyz'
    filename2 = '.'.join(filename.split('.')[:-1]) + suffix
    try:
        fn2 = open(filename2,'w')
    except IOError:
        print('Fatal error: cannot open output file ' + filename2 + ' !')
        exit(3)

    # Read all lines to deduce how many atoms there are
    lines = fn.readlines()
    lines = lines[1:] # remove the first line 'GEOM'
    fn.close()
    natom = len(lines)
    for line in lines:
        if "NATOM" in line:
            natom = int(line.strip("\n").split()[1])
       
    if do_gjf:
        fn2.write('# hf/sto-3g units=bohr\n')
        fn2.write('\n')
        fn2.write('GJF file generated by optgeom2xyz.py from ' + filename + '\n')
        fn2.write('\n')
        fn2.write('0 1\n')
        for line in lines:
            if "NATOM" in line: break
            fn2.write(line)
        fn2.write('\n')
        fn2.write('\n')
    else:
        fn2.write(str(natom) + '\n')
        fn2.write('XYZ file generated by optgeom2xyz.py from ' + filename + '\n')
        for line in lines:
            if "NATOM" in line: break
            coord = line.split()
            for i in range(1,4):
                coord[i] = '%5.12f' % (float(coord[i])*0.52917721092)
            line = '    '.join(coord)
            fn2.write(line + '\n')
        
    fn2.close()

